# Generated by Django 3.2.10 on 2022-04-07 16:20

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Автор')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('reader', models.CharField(max_length=100, verbose_name='Чтец')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='О книге')),
                ('copyright_holder', models.CharField(max_length=100, verbose_name='правообладатель')),
                ('book', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Книга')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.author', verbose_name='Автор')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='data.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Отзывыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(choices=[('1', '7 Дней'), ('2', '14 Дней'), ('3', '30 Дней'), ('4', '365 Дней')], max_length=50, verbose_name='За период')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.book', verbose_name='Я прочитаю')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
