# Generated by Django 3.2.10 on 2022-04-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20220410_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Аудио', 'verbose_name_plural': 'Аудио'},
        ),
        migrations.AlterField(
            model_name='audio',
            name='year_book',
            field=models.CharField(max_length=4, verbose_name='Год выпуска книги'),
        ),
    ]
