# Generated by Django 3.2.10 on 2022-04-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20220411_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceaudio',
            options={'verbose_name': 'Аудио версия', 'verbose_name_plural': 'Аудио версии'},
        ),
    ]
