# Generated by Django 3.2.10 on 2022-04-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_choiceaudio_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='book',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.URLField(default=1, verbose_name='Книга'),
            preserve_default=False,
        ),
    ]
