# Generated by Django 3.2.10 on 2022-04-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20220411_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.URLField(verbose_name='Аудио версия'),
        ),
    ]
