# Generated by Django 3.2.10 on 2022-04-11 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0011_alter_audio_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='author',
        ),
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.ManyToManyField(to='data.Author', verbose_name='Автор'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='data.Author', verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='PhotoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='фотография пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
