# Generated by Django 3.2.10 on 2022-04-11 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('data', '0012_auto_20220411_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('reader', models.CharField(max_length=100, verbose_name='Чтец')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='О книге')),
                ('copyright_holder', models.CharField(max_length=100, verbose_name='правообладатель')),
                ('audio', models.URLField(verbose_name='Аудио версия')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('year_book', models.CharField(max_length=4, verbose_name='Год выпуска книги')),
                ('age_view', models.CharField(max_length=3, verbose_name='рекомендуется к просмотру')),
                ('author', models.ManyToManyField(to='data.Author', verbose_name='Автор')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
            },
        ),
        migrations.AlterField(
            model_name='choiceaudio',
            name='audio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.audiobook', verbose_name='Книга'),
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
