# Generated by Django 3.2.10 on 2022-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20220411_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinggoal',
            name='book',
        ),
        migrations.AddField(
            model_name='readinggoal',
            name='goal',
            field=models.IntegerField(default=1, verbose_name='Я прочитаю'),
            preserve_default=False,
        ),
    ]
