# Generated by Django 3.2.10 on 2022-04-28 18:53

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Автор')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('date_dead', models.DateField(verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='О книге')),
                ('copyright_holder', models.CharField(max_length=100, verbose_name='правообладатель')),
                ('book', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Книга')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('year_book', models.DateField(verbose_name='Дата выхода')),
                ('age_view', models.PositiveSmallIntegerField(max_length=3, verbose_name='рекомендуется к просмотру')),
                ('book_type', models.CharField(choices=[('1', 'Бесплатно'), ('2', 'Премиум')], max_length=100, verbose_name='Тип книги')),
                ('author', models.ManyToManyField(to='book.Author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('rating', models.PositiveSmallIntegerField(max_length=100, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('book_type', models.CharField(choices=[('1', 'Бесплатно'), ('2', 'Премиум')], max_length=100, verbose_name='Тип книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Список книг',
                'verbose_name_plural': 'Список книг',
            },
        ),
        migrations.CreateModel(
            name='VideoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Видео')),
                ('video', models.URLField(verbose_name='Видео')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.booklist', verbose_name='Список книг')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('like', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Отзывыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(verbose_name='Я прочитаю')),
                ('time_period', models.CharField(choices=[('1', '7 Дней'), ('2', '14 Дней'), ('3', '30 Дней'), ('4', '365 Дней')], max_length=50, verbose_name='За период')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='PhotoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='фотография пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.booklist', verbose_name='Список книг'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('reader', models.CharField(max_length=100, verbose_name='Чтец')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='О книге')),
                ('copyright_holder', models.CharField(max_length=100, verbose_name='правообладатель')),
                ('audio', models.URLField(verbose_name='Аудио версия')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('year_book', models.CharField(max_length=4, verbose_name='Год выпуска книги')),
                ('age_view', models.CharField(max_length=3, verbose_name='рекомендуется к просмотру')),
                ('book_type', models.CharField(choices=[('1', 'Бесплатно'), ('2', 'Премиум')], max_length=100, verbose_name='Тип книги')),
                ('author', models.ManyToManyField(to='book.Author', verbose_name='Автор')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.booklist', verbose_name='Список книг')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
            },
        ),
    ]
