# Generated by Django 3.2.10 on 2022-04-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220430_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='book_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.booklist', verbose_name='Список книг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
