# Generated by Django 3.2.10 on 2022-04-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220430_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.review', verbose_name='Отзыв'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readbook',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_detail', to='book.review', verbose_name='Отзыв'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videobook',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.review', verbose_name='Отзыв'),
            preserve_default=False,
        ),
    ]
