# Generated by Django 3.2.10 on 2022-04-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220430_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='review',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='review',
        ),
        migrations.RemoveField(
            model_name='videobook',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='read_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.readbook', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='age_view',
            field=models.CharField(max_length=3, verbose_name='рекомендуется к просмотру'),
        ),
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
    ]
