# Generated by Django 3.2.10 on 2022-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220430_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='review',
            name='audio_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.audiobook', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='video_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.videobook', verbose_name='Книга'),
            preserve_default=False,
        ),
    ]
