# Generated by Django 3.2.10 on 2022-04-29 22:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_auto_20220430_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('like', models.BooleanField(blank=True, default=False, null=True, verbose_name='Лайк')),
                ('audio_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.audiobook', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Отзывыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('like', models.BooleanField(blank=True, default=False, null=True, verbose_name='Лайк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('video_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.readbook', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзывыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('like', models.BooleanField(blank=True, default=False, null=True, verbose_name='Лайк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('video_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.videobook', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзывыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
