# Generated by Django 3.2.10 on 2022-04-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220430_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewbook',
            name='video_book',
        ),
        migrations.AddField(
            model_name='reviewbook',
            name='read_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_book_detail', to='book.readbook', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewaudio',
            name='audio_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_audio_detail', to='book.audiobook', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='video_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_video_detail', to='book.videobook', verbose_name='Книга'),
        ),
    ]
