# Generated by Django 3.2.10 on 2022-04-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220430_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='tags',
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_audio_detail', to='book.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_read_detail', to='book.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='videobook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_video_detail', to='book.author', verbose_name='Автор'),
        ),
    ]
