# Generated by Django 3.2.10 on 2022-04-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20220430_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='book_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_list_detail', to='book.booklist', verbose_name='Список книг'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detail', to='book.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='book_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_book_detail', to='book.booklist', verbose_name='Список книг'),
        ),
        migrations.AlterField(
            model_name='videobook',
            name='booklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_video_detail', to='book.booklist', verbose_name='Список книг'),
        ),
    ]
