# Generated by Django 4.0.6 on 2022-07-22 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_alter_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='books', through='book.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
