# Generated by Django 4.0.6 on 2022-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
