# Generated by Django 4.0.6 on 2022-07-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
